/* Cartera de ejemplo (empresas ficticias) repartida por la península ibérica.
   Sirve para probar la app sin cargar datos reales. */
window.BTP = window.BTP || {};
(function (BTP) {
  'use strict';
  BTP.demoData = [
  {
    "name": "Soluciones Andalusí S.L.",
    "contact": "Carlos Ribeiro",
    "title": "Director Comercial",
    "address": "Calle Mayor 23",
    "postal": "",
    "city": "Madrid",
    "province": "Madrid",
    "country": "España",
    "phone": "+34 965 528 171",
    "email": "contacto@empresa01.example",
    "website": "www.empresa01.example",
    "industry": "Tecnología",
    "type": "cliente",
    "priority": 2,
    "value": 120000,
    "lastVisit": "2024-11-16",
    "duration": 45,
    "notes": "",
    "lat": 40.36769,
    "lng": -3.71286,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Energía Aurora Group",
    "contact": "Carlos Ferreira",
    "title": "Director de Compras",
    "address": "Paseo de la Constitución 35",
    "postal": "",
    "city": "Madrid",
    "province": "Madrid",
    "country": "España",
    "phone": "+34 947 529 247",
    "email": "contacto@empresa02.example",
    "website": "www.empresa02.example",
    "industry": "Energía",
    "type": "prospecto",
    "priority": 2,
    "value": 180000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 40.42531,
    "lng": -3.69657,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Metálicas Serena Group",
    "contact": "Marta Ortega",
    "title": "Director de Compras",
    "address": "Calle Colón 53",
    "postal": "",
    "city": "Madrid",
    "province": "Madrid",
    "country": "España",
    "phone": "+34 973 796 644",
    "email": "contacto@empresa03.example",
    "website": "www.empresa03.example",
    "industry": "Metalurgia",
    "type": "prospecto",
    "priority": 2,
    "value": 400000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 40.45007,
    "lng": -3.70793,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Digital Aurora S.A.",
    "contact": "Inês Mota",
    "title": "Responsable de Calidad",
    "address": "Rua da Liberdade 115",
    "postal": "",
    "city": "Alcobendas",
    "province": "Madrid",
    "country": "España",
    "phone": "+34 946 723 174",
    "email": "contacto@empresa04.example",
    "website": "www.empresa04.example",
    "industry": "Tecnología",
    "type": "prospecto",
    "priority": 3,
    "value": 90000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 40.54893,
    "lng": -3.6821,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Farma Norte S.L.",
    "contact": "Nuria Iglesias",
    "title": "Responsable de Mantenimiento",
    "address": "Calle Colón 117",
    "postal": "",
    "city": "Getafe",
    "province": "Madrid",
    "country": "España",
    "phone": "+34 918 960 195",
    "email": "contacto@empresa05.example",
    "website": "www.empresa05.example",
    "industry": "Farmacéutico",
    "type": "prospecto",
    "priority": 2,
    "value": 120000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 40.30509,
    "lng": -3.7128,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Agroindustrial Serena & Cía.",
    "contact": "Cristina Iglesias",
    "title": "Gerente",
    "address": "Calle Colón 30",
    "postal": "",
    "city": "Getafe",
    "province": "Madrid",
    "country": "España",
    "phone": "+34 973 160 323",
    "email": "contacto@empresa06.example",
    "website": "www.empresa06.example",
    "industry": "Industria alimentaria",
    "type": "cliente",
    "priority": 2,
    "value": 120000,
    "lastVisit": "2026-06-12",
    "duration": 60,
    "notes": "",
    "lat": 40.26372,
    "lng": -3.76279,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Laboratorios Ebro & Cía.",
    "contact": "Tiago Silva",
    "title": "Director Financiero",
    "address": "Calle Real 175",
    "postal": "",
    "city": "Guadalajara",
    "province": "Guadalajara",
    "country": "España",
    "phone": "+34 958 336 254",
    "email": "contacto@empresa07.example",
    "website": "www.empresa07.example",
    "industry": "Farmacéutico",
    "type": "cliente",
    "priority": 3,
    "value": 40000,
    "lastVisit": "2025-04-21",
    "duration": null,
    "notes": "",
    "lat": 40.59045,
    "lng": -3.19357,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Construcciones Occidental Group",
    "contact": "Tiago Iglesias",
    "title": "Responsable de Calidad",
    "address": "Polígono Industrial Las Fuentes 177",
    "postal": "",
    "city": "Guadalajara",
    "province": "Guadalajara",
    "country": "España",
    "phone": "+34 975 732 770",
    "email": "contacto@empresa08.example",
    "website": "www.empresa08.example",
    "industry": "Construcción",
    "type": "cliente",
    "priority": 3,
    "value": 40000,
    "lastVisit": "2025-05-02",
    "duration": null,
    "notes": "",
    "lat": 40.6241,
    "lng": -3.11688,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Restauración Andalusí & Cía.",
    "contact": "Elena López",
    "title": "Director Comercial",
    "address": "Camino de la Estación 42",
    "postal": "",
    "city": "Toledo",
    "province": "Toledo",
    "country": "España",
    "phone": "+34 924 448 715",
    "email": "contacto@empresa09.example",
    "website": "www.empresa09.example",
    "industry": "Hostelería",
    "type": "cliente",
    "priority": 2,
    "value": 180000,
    "lastVisit": "2026-05-03",
    "duration": null,
    "notes": "",
    "lat": 39.81509,
    "lng": -4.01929,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Sistemas Levante S.A.",
    "contact": "Andrés Cano",
    "title": "Responsable de Calidad",
    "address": "Camino de la Estación 32",
    "postal": "",
    "city": "Ávila",
    "province": "Ávila",
    "country": "España",
    "phone": "+34 924 969 599",
    "email": "contacto@empresa10.example",
    "website": "www.empresa10.example",
    "industry": "Tecnología",
    "type": "prospecto",
    "priority": 3,
    "value": 90000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 40.65415,
    "lng": -4.70438,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Digital Occidental S.A.",
    "contact": "Andrés Pérez",
    "title": "Director de Compras",
    "address": "Avenida da República 136",
    "postal": "",
    "city": "Segovia",
    "province": "Segovia",
    "country": "España",
    "phone": "+34 948 758 984",
    "email": "contacto@empresa11.example",
    "website": "www.empresa11.example",
    "industry": "Tecnología",
    "type": "prospecto",
    "priority": 3,
    "value": 400000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 40.96644,
    "lng": -4.13747,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Soluciones Trébol S.A.",
    "contact": "Pablo Cano",
    "title": "Director Comercial",
    "address": "Avenida da República 62",
    "postal": "",
    "city": "Segovia",
    "province": "Segovia",
    "country": "España",
    "phone": "+34 961 857 922",
    "email": "contacto@empresa12.example",
    "website": "www.empresa12.example",
    "industry": "Tecnología",
    "type": "prospecto",
    "priority": 1,
    "value": 120000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 40.90689,
    "lng": -4.10967,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Agroindustrial Occidental S.L.U.",
    "contact": "Andrés Iglesias",
    "title": "Responsable de Operaciones",
    "address": "Calle Alcalá 27",
    "postal": "",
    "city": "Valladolid",
    "province": "Valladolid",
    "country": "España",
    "phone": "+34 939 581 301",
    "email": "contacto@empresa13.example",
    "website": "www.empresa13.example",
    "industry": "Industria alimentaria",
    "type": "cliente",
    "priority": 2,
    "value": 120000,
    "lastVisit": "2025-04-04",
    "duration": 60,
    "notes": "",
    "lat": 41.61682,
    "lng": -4.70961,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Delicias Trébol S.L.",
    "contact": "Elena Mota",
    "title": "Gerente",
    "address": "Ronda Sur 163",
    "postal": "",
    "city": "Burgos",
    "province": "Burgos",
    "country": "España",
    "phone": "+34 952 188 920",
    "email": "contacto@empresa14.example",
    "website": "www.empresa14.example",
    "industry": "Industria alimentaria",
    "type": "prospecto",
    "priority": 3,
    "value": 180000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 42.33948,
    "lng": -3.6677,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Aceros Duero S.L.",
    "contact": "Miguel Mota",
    "title": "Responsable de Calidad",
    "address": "Polígono Industrial Las Fuentes 141",
    "postal": "",
    "city": "Salamanca",
    "province": "Salamanca",
    "country": "España",
    "phone": "+34 926 121 114",
    "email": "contacto@empresa15.example",
    "website": "www.empresa15.example",
    "industry": "Metalurgia",
    "type": "cliente",
    "priority": 1,
    "value": 40000,
    "lastVisit": "2024-10-17",
    "duration": null,
    "notes": "",
    "lat": 40.97329,
    "lng": -5.61147,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Componentes Mediterránea S.L.",
    "contact": "Nuria Silva",
    "title": "Director Financiero",
    "address": "Travessa do Comércio 34",
    "postal": "",
    "city": "Salamanca",
    "province": "Salamanca",
    "country": "España",
    "phone": "+34 917 857 462",
    "email": "contacto@empresa16.example",
    "website": "www.empresa16.example",
    "industry": "Automoción",
    "type": "cliente",
    "priority": 3,
    "value": 60000,
    "lastVisit": "2024-11-12",
    "duration": 90,
    "notes": "",
    "lat": 40.9896,
    "lng": -5.62569,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Hoteles Guadiana S.A.",
    "contact": "Sergio Cano",
    "title": "Director de Compras",
    "address": "Avenida da República 39",
    "postal": "",
    "city": "León",
    "province": "León",
    "country": "España",
    "phone": "+34 932 244 584",
    "email": "contacto@empresa17.example",
    "website": "www.empresa17.example",
    "industry": "Hostelería",
    "type": "prospecto",
    "priority": 3,
    "value": 250000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 42.60548,
    "lng": -5.58798,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Grupo Guadiana & Cía.",
    "contact": "Carlos Ferreira",
    "title": "Director Comercial",
    "address": "Avenida del Puerto 11",
    "postal": "",
    "city": "Zaragoza",
    "province": "Zaragoza",
    "country": "España",
    "phone": "+34 922 619 563",
    "email": "contacto@empresa18.example",
    "website": "www.empresa18.example",
    "industry": "Hostelería",
    "type": "prospecto",
    "priority": 3,
    "value": 400000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 41.68,
    "lng": -0.8396,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Farma Alba Group",
    "contact": "Cristina Ribeiro",
    "title": "Responsable de Mantenimiento",
    "address": "Paseo de la Constitución 64",
    "postal": "",
    "city": "Zaragoza",
    "province": "Zaragoza",
    "country": "España",
    "phone": "+34 976 997 997",
    "email": "contacto@empresa19.example",
    "website": "www.empresa19.example",
    "industry": "Farmacéutico",
    "type": "prospecto",
    "priority": 3,
    "value": 90000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 41.69953,
    "lng": -0.84197,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Proyectos Duero & Cía.",
    "contact": "Jorge López",
    "title": "Director Comercial",
    "address": "Avenida de Europa 78",
    "postal": "",
    "city": "Zaragoza",
    "province": "Zaragoza",
    "country": "España",
    "phone": "+34 925 895 258",
    "email": "contacto@empresa20.example",
    "website": "www.empresa20.example",
    "industry": "Construcción",
    "type": "cliente",
    "priority": 2,
    "value": 25000,
    "lastVisit": "2025-11-01",
    "duration": 60,
    "notes": "",
    "lat": 41.60596,
    "lng": -0.84316,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Construcciones Andalusí & Cía.",
    "contact": "Jorge Ribeiro",
    "title": "Director Financiero",
    "address": "Calle Real 108",
    "postal": "",
    "city": "Huesca",
    "province": "Huesca",
    "country": "España",
    "phone": "+34 935 465 426",
    "email": "contacto@empresa21.example",
    "website": "www.empresa21.example",
    "industry": "Construcción",
    "type": "cliente",
    "priority": 2,
    "value": 60000,
    "lastVisit": "2026-01-21",
    "duration": null,
    "notes": "",
    "lat": 42.16676,
    "lng": -0.46656,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Biotech Ibérica & Cía.",
    "contact": "Javier Ferreira",
    "title": "Responsable de Operaciones",
    "address": "Avenida de la Industria 68",
    "postal": "",
    "city": "Logroño",
    "province": "La Rioja",
    "country": "España",
    "phone": "+34 944 140 897",
    "email": "contacto@empresa22.example",
    "website": "www.empresa22.example",
    "industry": "Farmacéutico",
    "type": "cliente",
    "priority": 2,
    "value": 400000,
    "lastVisit": "2026-05-01",
    "duration": 45,
    "notes": "",
    "lat": 42.43515,
    "lng": -2.48935,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Distribuciones Duero Group",
    "contact": "Marta Silva",
    "title": "Director de Compras",
    "address": "Avenida da República 177",
    "postal": "",
    "city": "Pamplona",
    "province": "Navarra",
    "country": "España",
    "phone": "+34 933 535 174",
    "email": "contacto@empresa23.example",
    "website": "www.empresa23.example",
    "industry": "Retail",
    "type": "prospecto",
    "priority": 2,
    "value": 120000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 42.8651,
    "lng": -1.62967,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Comercial Alba S.A.",
    "contact": "Nuria Blanco",
    "title": "Director Financiero",
    "address": "Avenida del Puerto 160",
    "postal": "",
    "city": "Pamplona",
    "province": "Navarra",
    "country": "España",
    "phone": "+34 926 144 639",
    "email": "contacto@empresa24.example",
    "website": "www.empresa24.example",
    "industry": "Retail",
    "type": "cliente",
    "priority": 1,
    "value": 250000,
    "lastVisit": "2026-06-24",
    "duration": 45,
    "notes": "",
    "lat": 42.86508,
    "lng": -1.58949,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Aceros Vega S.L.U.",
    "contact": "Inês Gómez",
    "title": "Jefe de Planta",
    "address": "Calle Real 5",
    "postal": "",
    "city": "Vitoria-Gasteiz",
    "province": "Álava",
    "country": "España",
    "phone": "+34 942 137 115",
    "email": "contacto@empresa25.example",
    "website": "www.empresa25.example",
    "industry": "Metalurgia",
    "type": "prospecto",
    "priority": 3,
    "value": 250000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 42.87467,
    "lng": -2.66547,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Proyectos Aurora & Cía.",
    "contact": "Tiago Domínguez",
    "title": "Jefe de Planta",
    "address": "Rua da Liberdade 56",
    "postal": "",
    "city": "Vitoria-Gasteiz",
    "province": "Álava",
    "country": "España",
    "phone": "+34 939 450 303",
    "email": "contacto@empresa26.example",
    "website": "www.empresa26.example",
    "industry": "Construcción",
    "type": "cliente",
    "priority": 1,
    "value": 180000,
    "lastVisit": "2025-02-14",
    "duration": 45,
    "notes": "",
    "lat": 42.83526,
    "lng": -2.68989,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Alimentaria Ibérica S.L.",
    "contact": "Sergio Martínez",
    "title": "Responsable de Operaciones",
    "address": "Avenida de Europa 98",
    "postal": "",
    "city": "Bilbao",
    "province": "Bizkaia",
    "country": "España",
    "phone": "+34 974 786 388",
    "email": "contacto@empresa27.example",
    "website": "www.empresa27.example",
    "industry": "Industria alimentaria",
    "type": "prospecto",
    "priority": 1,
    "value": 180000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 43.28612,
    "lng": -2.98957,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Aceros Castellana & Cía.",
    "contact": "Nuria Ferreira",
    "title": "Director de Compras",
    "address": "Avenida del Puerto 56",
    "postal": "",
    "city": "Bilbao",
    "province": "Bizkaia",
    "country": "España",
    "phone": "+34 955 287 101",
    "email": "contacto@empresa28.example",
    "website": "www.empresa28.example",
    "industry": "Metalurgia",
    "type": "cliente",
    "priority": 2,
    "value": 120000,
    "lastVisit": "2024-12-22",
    "duration": 60,
    "notes": "",
    "lat": 43.2488,
    "lng": -2.93804,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Grupo Mediterránea S.A.",
    "contact": "Marta Pérez",
    "title": "Director Financiero",
    "address": "Calle Colón 11",
    "postal": "",
    "city": "Bilbao",
    "province": "Bizkaia",
    "country": "España",
    "phone": "+34 960 123 406",
    "email": "contacto@empresa29.example",
    "website": "www.empresa29.example",
    "industry": "Hostelería",
    "type": "prospecto",
    "priority": 3,
    "value": 90000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 43.27856,
    "lng": -2.98486,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Mecanizados Peninsular & Cía.",
    "contact": "Inês Vidal",
    "title": "Gerente",
    "address": "Paseo de la Constitución 130",
    "postal": "",
    "city": "San Sebastián",
    "province": "Gipuzkoa",
    "country": "España",
    "phone": "+34 912 946 802",
    "email": "contacto@empresa30.example",
    "website": "www.empresa30.example",
    "industry": "Metalurgia",
    "type": "cliente",
    "priority": 2,
    "value": 40000,
    "lastVisit": "2026-05-22",
    "duration": 45,
    "notes": "",
    "lat": 43.26851,
    "lng": -2.03618,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Distribución Tajo Group",
    "contact": "Rui Silva",
    "title": "Director de Compras",
    "address": "Camino de la Estación 18",
    "postal": "",
    "city": "Santander",
    "province": "Cantabria",
    "country": "España",
    "phone": "+34 974 648 194",
    "email": "contacto@empresa31.example",
    "website": "www.empresa31.example",
    "industry": "Logística y transporte",
    "type": "cliente",
    "priority": 3,
    "value": 400000,
    "lastVisit": "2025-10-28",
    "duration": null,
    "notes": "",
    "lat": 43.49179,
    "lng": -3.81314,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Comercial Mediterránea S.A.",
    "contact": "Beatriz López",
    "title": "Responsable de Mantenimiento",
    "address": "Avenida de Europa 74",
    "postal": "",
    "city": "Gijón",
    "province": "Asturias",
    "country": "España",
    "phone": "+34 915 731 747",
    "email": "contacto@empresa32.example",
    "website": "www.empresa32.example",
    "industry": "Retail",
    "type": "prospecto",
    "priority": 1,
    "value": 250000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 43.4815,
    "lng": -5.70341,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Suministros Serena S.A.",
    "contact": "Elena Mota",
    "title": "Jefe de Planta",
    "address": "Rua da Liberdade 133",
    "postal": "",
    "city": "Oviedo",
    "province": "Asturias",
    "country": "España",
    "phone": "+34 946 575 577",
    "email": "contacto@empresa33.example",
    "website": "www.empresa33.example",
    "industry": "Retail",
    "type": "cliente",
    "priority": 3,
    "value": 90000,
    "lastVisit": "2026-03-26",
    "duration": 90,
    "notes": "",
    "lat": 43.39396,
    "lng": -5.7902,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Hoteles Vega S.L.",
    "contact": "Marta Ribeiro",
    "title": "Responsable de Mantenimiento",
    "address": "Avenida del Puerto 100",
    "postal": "",
    "city": "Oviedo",
    "province": "Asturias",
    "country": "España",
    "phone": "+34 936 315 176",
    "email": "contacto@empresa34.example",
    "website": "www.empresa34.example",
    "industry": "Hostelería",
    "type": "prospecto",
    "priority": 3,
    "value": 250000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 43.31891,
    "lng": -5.84651,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Forja Atlántica S.L.U.",
    "contact": "Ana Gómez",
    "title": "Director de Compras",
    "address": "Camino de la Estación 175",
    "postal": "",
    "city": "A Coruña",
    "province": "A Coruña",
    "country": "España",
    "phone": "+34 967 515 409",
    "email": "contacto@empresa35.example",
    "website": "www.empresa35.example",
    "industry": "Metalurgia",
    "type": "cliente",
    "priority": 1,
    "value": 250000,
    "lastVisit": "2025-05-28",
    "duration": 45,
    "notes": "",
    "lat": 43.35224,
    "lng": -8.42637,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Sistemas Peninsular S.L.U.",
    "contact": "Ana Costa",
    "title": "Jefe de Planta",
    "address": "Calle Real 17",
    "postal": "",
    "city": "Santiago de Compostela",
    "province": "A Coruña",
    "country": "España",
    "phone": "+34 960 499 990",
    "email": "contacto@empresa36.example",
    "website": "www.empresa36.example",
    "industry": "Tecnología",
    "type": "prospecto",
    "priority": 3,
    "value": 60000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 42.86149,
    "lng": -8.55343,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Comercial Castellana S.L.",
    "contact": "Rocío Vidal",
    "title": "Responsable de Calidad",
    "address": "Calle Alcalá 96",
    "postal": "",
    "city": "Santiago de Compostela",
    "province": "A Coruña",
    "country": "España",
    "phone": "+34 964 129 931",
    "email": "contacto@empresa37.example",
    "website": "www.empresa37.example",
    "industry": "Retail",
    "type": "cliente",
    "priority": 2,
    "value": 40000,
    "lastVisit": "2025-10-23",
    "duration": 90,
    "notes": "",
    "lat": 42.92781,
    "lng": -8.49192,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Logística Miño & Cía.",
    "contact": "Rui Martínez",
    "title": "Gerente",
    "address": "Polígono Industrial Las Fuentes 121",
    "postal": "",
    "city": "Vigo",
    "province": "Pontevedra",
    "country": "España",
    "phone": "+34 963 451 388",
    "email": "contacto@empresa38.example",
    "website": "www.empresa38.example",
    "industry": "Logística y transporte",
    "type": "prospecto",
    "priority": 3,
    "value": 90000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 42.21129,
    "lng": -8.69205,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Automoción Aurora S.L.U.",
    "contact": "Sergio Gómez",
    "title": "Responsable de Operaciones",
    "address": "Calle Alcalá 129",
    "postal": "",
    "city": "Ourense",
    "province": "Ourense",
    "country": "España",
    "phone": "+34 973 663 325",
    "email": "contacto@empresa39.example",
    "website": "www.empresa39.example",
    "industry": "Automoción",
    "type": "prospecto",
    "priority": 2,
    "value": 25000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 42.38455,
    "lng": -7.80432,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Farma Duero Group",
    "contact": "Marta Navarro",
    "title": "Director Comercial",
    "address": "Calle Real 67",
    "postal": "",
    "city": "Barcelona",
    "province": "Barcelona",
    "country": "España",
    "phone": "+34 935 120 867",
    "email": "contacto@empresa40.example",
    "website": "www.empresa40.example",
    "industry": "Farmacéutico",
    "type": "cliente",
    "priority": 3,
    "value": 120000,
    "lastVisit": "2024-12-13",
    "duration": 90,
    "notes": "",
    "lat": 41.37334,
    "lng": 2.1981,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Proyectos Castellana S.L.U.",
    "contact": "Lucía Ribeiro",
    "title": "Director Comercial",
    "address": "Avenida de la Industria 70",
    "postal": "",
    "city": "Barcelona",
    "province": "Barcelona",
    "country": "España",
    "phone": "+34 941 493 509",
    "email": "contacto@empresa41.example",
    "website": "www.empresa41.example",
    "industry": "Construcción",
    "type": "prospecto",
    "priority": 2,
    "value": 120000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 41.37922,
    "lng": 2.14604,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Alimentaria Norte & Cía.",
    "contact": "Sofia Mota",
    "title": "Director de Compras",
    "address": "Avenida de la Industria 101",
    "postal": "",
    "city": "Barcelona",
    "province": "Barcelona",
    "country": "España",
    "phone": "+34 977 975 579",
    "email": "contacto@empresa42.example",
    "website": "www.empresa42.example",
    "industry": "Industria alimentaria",
    "type": "prospecto",
    "priority": 1,
    "value": 250000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 41.35722,
    "lng": 2.12169,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Grupo Atlántica & Cía.",
    "contact": "Pablo Ortega",
    "title": "Director de Compras",
    "address": "Avenida de Europa 78",
    "postal": "",
    "city": "Sabadell",
    "province": "Barcelona",
    "country": "España",
    "phone": "+34 926 741 357",
    "email": "contacto@empresa43.example",
    "website": "www.empresa43.example",
    "industry": "Hostelería",
    "type": "cliente",
    "priority": 1,
    "value": 15000,
    "lastVisit": "2026-02-27",
    "duration": 90,
    "notes": "",
    "lat": 41.56713,
    "lng": 2.06286,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Cargo Cantábrica Group",
    "contact": "Tiago Costa",
    "title": "Responsable de Mantenimiento",
    "address": "Avenida del Puerto 81",
    "postal": "",
    "city": "Sabadell",
    "province": "Barcelona",
    "country": "España",
    "phone": "+34 941 586 638",
    "email": "contacto@empresa44.example",
    "website": "www.empresa44.example",
    "industry": "Logística y transporte",
    "type": "cliente",
    "priority": 3,
    "value": 15000,
    "lastVisit": "2026-06-25",
    "duration": 45,
    "notes": "",
    "lat": 41.54894,
    "lng": 2.05291,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Comercial Ibérica S.A.",
    "contact": "Marta Silva",
    "title": "Director Comercial",
    "address": "Avenida de Europa 109",
    "postal": "",
    "city": "Girona",
    "province": "Girona",
    "country": "España",
    "phone": "+34 957 332 604",
    "email": "contacto@empresa45.example",
    "website": "www.empresa45.example",
    "industry": "Retail",
    "type": "prospecto",
    "priority": 2,
    "value": 180000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 42.0029,
    "lng": 2.8476,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Datos Mediterránea S.L.",
    "contact": "Marta Ruiz",
    "title": "Responsable de Mantenimiento",
    "address": "Calle Alcalá 80",
    "postal": "",
    "city": "Girona",
    "province": "Girona",
    "country": "España",
    "phone": "+34 934 336 576",
    "email": "contacto@empresa46.example",
    "website": "www.empresa46.example",
    "industry": "Tecnología",
    "type": "prospecto",
    "priority": 2,
    "value": 400000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 41.9512,
    "lng": 2.86812,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Solar Alba S.A.",
    "contact": "Miguel Pérez",
    "title": "Director Financiero",
    "address": "Calle Mayor 55",
    "postal": "",
    "city": "Lleida",
    "province": "Lleida",
    "country": "España",
    "phone": "+34 913 710 245",
    "email": "contacto@empresa47.example",
    "website": "www.empresa47.example",
    "industry": "Energía",
    "type": "prospecto",
    "priority": 2,
    "value": 15000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 41.56382,
    "lng": 0.56722,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Motor Peninsular S.L.",
    "contact": "Elena Gómez",
    "title": "Responsable de Mantenimiento",
    "address": "Calle Mayor 80",
    "postal": "",
    "city": "Lleida",
    "province": "Lleida",
    "country": "España",
    "phone": "+34 958 959 482",
    "email": "contacto@empresa48.example",
    "website": "www.empresa48.example",
    "industry": "Automoción",
    "type": "prospecto",
    "priority": 1,
    "value": 120000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 41.61069,
    "lng": 0.57307,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Cargo Miño S.L.",
    "contact": "Andrés Costa",
    "title": "Director Financiero",
    "address": "Avenida de la Industria 13",
    "postal": "",
    "city": "Tarragona",
    "province": "Tarragona",
    "country": "España",
    "phone": "+34 970 300 481",
    "email": "contacto@empresa49.example",
    "website": "www.empresa49.example",
    "industry": "Logística y transporte",
    "type": "prospecto",
    "priority": 1,
    "value": 180000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 41.08206,
    "lng": 1.22821,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Laboratorios Miño S.A.",
    "contact": "Beatriz Martínez",
    "title": "Responsable de Mantenimiento",
    "address": "Avenida de la Industria 16",
    "postal": "",
    "city": "Tarragona",
    "province": "Tarragona",
    "country": "España",
    "phone": "+34 942 299 865",
    "email": "contacto@empresa50.example",
    "website": "www.empresa50.example",
    "industry": "Farmacéutico",
    "type": "prospecto",
    "priority": 1,
    "value": 15000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 41.16673,
    "lng": 1.22519,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Energía Castellana S.L.U.",
    "contact": "Ana Ferreira",
    "title": "Responsable de Operaciones",
    "address": "Camino de la Estación 120",
    "postal": "",
    "city": "Castellón de la Plana",
    "province": "Castellón",
    "country": "España",
    "phone": "+34 959 908 357",
    "email": "contacto@empresa51.example",
    "website": "www.empresa51.example",
    "industry": "Energía",
    "type": "prospecto",
    "priority": 3,
    "value": 25000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 40.02418,
    "lng": -0.09538,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Laboratorios Ibérica S.L.U.",
    "contact": "Nuria Navarro",
    "title": "Responsable de Mantenimiento",
    "address": "Calle Real 153",
    "postal": "",
    "city": "Castellón de la Plana",
    "province": "Castellón",
    "country": "España",
    "phone": "+34 920 624 302",
    "email": "contacto@empresa52.example",
    "website": "www.empresa52.example",
    "industry": "Farmacéutico",
    "type": "prospecto",
    "priority": 1,
    "value": 60000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 40.01675,
    "lng": -0.08162,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Logística Occidental Group",
    "contact": "Javier López",
    "title": "Jefe de Planta",
    "address": "Calle Colón 22",
    "postal": "",
    "city": "Valencia",
    "province": "Valencia",
    "country": "España",
    "phone": "+34 936 198 531",
    "email": "contacto@empresa53.example",
    "website": "www.empresa53.example",
    "industry": "Logística y transporte",
    "type": "prospecto",
    "priority": 3,
    "value": 180000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 39.52851,
    "lng": -0.31965,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Aceros Duero & Cía.",
    "contact": "Tiago Sánchez",
    "title": "Jefe de Planta",
    "address": "Avenida del Puerto 72",
    "postal": "",
    "city": "Valencia",
    "province": "Valencia",
    "country": "España",
    "phone": "+34 944 481 360",
    "email": "contacto@empresa54.example",
    "website": "www.empresa54.example",
    "industry": "Metalurgia",
    "type": "prospecto",
    "priority": 1,
    "value": 60000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 39.4338,
    "lng": -0.40661,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Obras Duero S.L.U.",
    "contact": "Marta Domínguez",
    "title": "Jefe de Planta",
    "address": "Calle Alcalá 130",
    "postal": "",
    "city": "Valencia",
    "province": "Valencia",
    "country": "España",
    "phone": "+34 977 336 765",
    "email": "contacto@empresa55.example",
    "website": "www.empresa55.example",
    "industry": "Construcción",
    "type": "prospecto",
    "priority": 2,
    "value": 120000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 39.4883,
    "lng": -0.31739,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Laboratorios Tajo S.L.U.",
    "contact": "Elena Cano",
    "title": "Director Comercial",
    "address": "Avenida de la Industria 96",
    "postal": "",
    "city": "Alicante",
    "province": "Alicante",
    "country": "España",
    "phone": "+34 975 986 282",
    "email": "contacto@empresa56.example",
    "website": "www.empresa56.example",
    "industry": "Farmacéutico",
    "type": "cliente",
    "priority": 3,
    "value": 25000,
    "lastVisit": "2026-05-15",
    "duration": 90,
    "notes": "",
    "lat": 38.35757,
    "lng": -0.448,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Conservas Alba Group",
    "contact": "Carlos Ruiz",
    "title": "Jefe de Planta",
    "address": "Calle Mayor 154",
    "postal": "",
    "city": "Alicante",
    "province": "Alicante",
    "country": "España",
    "phone": "+34 936 934 111",
    "email": "contacto@empresa57.example",
    "website": "www.empresa57.example",
    "industry": "Industria alimentaria",
    "type": "cliente",
    "priority": 3,
    "value": 120000,
    "lastVisit": "2026-02-11",
    "duration": 60,
    "notes": "",
    "lat": 38.33428,
    "lng": -0.49638,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Transportes Norte & Cía.",
    "contact": "Beatriz Blanco",
    "title": "Gerente",
    "address": "Avenida de Europa 137",
    "postal": "",
    "city": "Elche",
    "province": "Alicante",
    "country": "España",
    "phone": "+34 921 768 267",
    "email": "contacto@empresa58.example",
    "website": "www.empresa58.example",
    "industry": "Logística y transporte",
    "type": "prospecto",
    "priority": 3,
    "value": 25000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 38.29335,
    "lng": -0.72343,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Distribuciones Norte S.L.U.",
    "contact": "Jorge García",
    "title": "Responsable de Calidad",
    "address": "Avenida de Europa 51",
    "postal": "",
    "city": "Murcia",
    "province": "Murcia",
    "country": "España",
    "phone": "+34 960 845 514",
    "email": "contacto@empresa59.example",
    "website": "www.empresa59.example",
    "industry": "Retail",
    "type": "prospecto",
    "priority": 1,
    "value": 180000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 38.04524,
    "lng": -1.1386,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Mecanizados Atlántica S.L.",
    "contact": "Lucía García",
    "title": "Director de Compras",
    "address": "Paseo de la Constitución 37",
    "postal": "",
    "city": "Murcia",
    "province": "Murcia",
    "country": "España",
    "phone": "+34 960 191 686",
    "email": "contacto@empresa60.example",
    "website": "www.empresa60.example",
    "industry": "Metalurgia",
    "type": "cliente",
    "priority": 1,
    "value": 250000,
    "lastVisit": "2026-01-20",
    "duration": 60,
    "notes": "",
    "lat": 38.02067,
    "lng": -1.1701,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Aceros Levante S.L.",
    "contact": "Lucía Martínez",
    "title": "Responsable de Mantenimiento",
    "address": "Calle Real 14",
    "postal": "",
    "city": "Albacete",
    "province": "Albacete",
    "country": "España",
    "phone": "+34 959 188 829",
    "email": "contacto@empresa61.example",
    "website": "www.empresa61.example",
    "industry": "Metalurgia",
    "type": "cliente",
    "priority": 1,
    "value": 60000,
    "lastVisit": "2025-08-31",
    "duration": 45,
    "notes": "",
    "lat": 39.01114,
    "lng": -1.81571,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Solar Alba S.A.",
    "contact": "Carlos Domínguez",
    "title": "Gerente",
    "address": "Ronda Sur 92",
    "postal": "",
    "city": "Albacete",
    "province": "Albacete",
    "country": "España",
    "phone": "+34 925 253 352",
    "email": "contacto@empresa62.example",
    "website": "www.empresa62.example",
    "industry": "Energía",
    "type": "prospecto",
    "priority": 3,
    "value": 60000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 38.93923,
    "lng": -1.85102,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Agroindustrial Atlántica & Cía.",
    "contact": "Jorge Costa",
    "title": "Director Comercial",
    "address": "Ronda Sur 100",
    "postal": "",
    "city": "Almería",
    "province": "Almería",
    "country": "España",
    "phone": "+34 957 557 615",
    "email": "contacto@empresa63.example",
    "website": "www.empresa63.example",
    "industry": "Industria alimentaria",
    "type": "prospecto",
    "priority": 2,
    "value": 90000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 36.79545,
    "lng": -2.52328,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Laboratorios Tajo Group",
    "contact": "Rui Domínguez",
    "title": "Responsable de Operaciones",
    "address": "Avenida de la Industria 33",
    "postal": "",
    "city": "Granada",
    "province": "Granada",
    "country": "España",
    "phone": "+34 955 540 474",
    "email": "contacto@empresa64.example",
    "website": "www.empresa64.example",
    "industry": "Farmacéutico",
    "type": "prospecto",
    "priority": 2,
    "value": 40000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 37.21357,
    "lng": -3.59808,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Alimentaria Levante S.L.U.",
    "contact": "Inês Domínguez",
    "title": "Gerente",
    "address": "Calle Mayor 17",
    "postal": "",
    "city": "Málaga",
    "province": "Málaga",
    "country": "España",
    "phone": "+34 924 298 234",
    "email": "contacto@empresa65.example",
    "website": "www.empresa65.example",
    "industry": "Industria alimentaria",
    "type": "prospecto",
    "priority": 2,
    "value": 15000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 36.69585,
    "lng": -4.38408,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Construcciones Trébol Group",
    "contact": "Cristina Pérez",
    "title": "Jefe de Planta",
    "address": "Paseo de la Constitución 123",
    "postal": "",
    "city": "Córdoba",
    "province": "Córdoba",
    "country": "España",
    "phone": "+34 936 706 369",
    "email": "contacto@empresa66.example",
    "website": "www.empresa66.example",
    "industry": "Construcción",
    "type": "prospecto",
    "priority": 3,
    "value": 90000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 37.86649,
    "lng": -4.83498,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Forja Peninsular & Cía.",
    "contact": "Carlos Iglesias",
    "title": "Responsable de Mantenimiento",
    "address": "Paseo de la Constitución 134",
    "postal": "",
    "city": "Jaén",
    "province": "Jaén",
    "country": "España",
    "phone": "+34 923 358 648",
    "email": "contacto@empresa67.example",
    "website": "www.empresa67.example",
    "industry": "Metalurgia",
    "type": "cliente",
    "priority": 1,
    "value": 25000,
    "lastVisit": "2025-01-08",
    "duration": 90,
    "notes": "",
    "lat": 37.80815,
    "lng": -3.80032,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Motor Serena S.A.",
    "contact": "Sergio Cano",
    "title": "Director de Compras",
    "address": "Avenida del Puerto 133",
    "postal": "",
    "city": "Jaén",
    "province": "Jaén",
    "country": "España",
    "phone": "+34 942 417 754",
    "email": "contacto@empresa68.example",
    "website": "www.empresa68.example",
    "industry": "Automoción",
    "type": "cliente",
    "priority": 1,
    "value": 250000,
    "lastVisit": "2025-11-12",
    "duration": 60,
    "notes": "",
    "lat": 37.80756,
    "lng": -3.75525,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Obras Vega Group",
    "contact": "Carlos Pérez",
    "title": "Responsable de Mantenimiento",
    "address": "Calle Alcalá 157",
    "postal": "",
    "city": "Sevilla",
    "province": "Sevilla",
    "country": "España",
    "phone": "+34 915 122 155",
    "email": "contacto@empresa69.example",
    "website": "www.empresa69.example",
    "industry": "Construcción",
    "type": "prospecto",
    "priority": 2,
    "value": 120000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 37.39715,
    "lng": -6.00805,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Restauración Guadiana S.A.",
    "contact": "Andrés Cano",
    "title": "Responsable de Mantenimiento",
    "address": "Polígono Industrial Las Fuentes 35",
    "postal": "",
    "city": "Sevilla",
    "province": "Sevilla",
    "country": "España",
    "phone": "+34 911 920 349",
    "email": "contacto@empresa70.example",
    "website": "www.empresa70.example",
    "industry": "Hostelería",
    "type": "cliente",
    "priority": 2,
    "value": 40000,
    "lastVisit": "2025-12-08",
    "duration": 45,
    "notes": "",
    "lat": 37.3832,
    "lng": -6.03686,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Forja Andalusí S.L.U.",
    "contact": "Andrés Cano",
    "title": "Responsable de Mantenimiento",
    "address": "Calle Colón 133",
    "postal": "",
    "city": "Sevilla",
    "province": "Sevilla",
    "country": "España",
    "phone": "+34 973 354 269",
    "email": "contacto@empresa71.example",
    "website": "www.empresa71.example",
    "industry": "Metalurgia",
    "type": "prospecto",
    "priority": 3,
    "value": 400000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 37.33438,
    "lng": -5.98072,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Obras Norte S.L.",
    "contact": "Jorge Ruiz",
    "title": "Director Financiero",
    "address": "Travessa do Comércio 157",
    "postal": "",
    "city": "Huelva",
    "province": "Huelva",
    "country": "España",
    "phone": "+34 932 620 416",
    "email": "contacto@empresa72.example",
    "website": "www.empresa72.example",
    "industry": "Construcción",
    "type": "cliente",
    "priority": 2,
    "value": 60000,
    "lastVisit": "2026-02-10",
    "duration": null,
    "notes": "",
    "lat": 37.23743,
    "lng": -6.99888,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Biotech Guadiana S.L.",
    "contact": "Cristina Gómez",
    "title": "Director Comercial",
    "address": "Avenida de la Industria 67",
    "postal": "",
    "city": "Huelva",
    "province": "Huelva",
    "country": "España",
    "phone": "+34 939 759 139",
    "email": "contacto@empresa73.example",
    "website": "www.empresa73.example",
    "industry": "Farmacéutico",
    "type": "cliente",
    "priority": 2,
    "value": 250000,
    "lastVisit": "2026-04-14",
    "duration": null,
    "notes": "",
    "lat": 37.24166,
    "lng": -6.91474,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Suministros Norte S.L.U.",
    "contact": "Rocío Costa",
    "title": "Director Comercial",
    "address": "Avenida de la Industria 130",
    "postal": "",
    "city": "Cádiz",
    "province": "Cádiz",
    "country": "España",
    "phone": "+34 911 273 366",
    "email": "contacto@empresa74.example",
    "website": "www.empresa74.example",
    "industry": "Retail",
    "type": "prospecto",
    "priority": 2,
    "value": 400000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 36.56811,
    "lng": -6.32427,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Soluciones Andalusí S.L.U.",
    "contact": "Rui Mota",
    "title": "Director de Compras",
    "address": "Travessa do Comércio 7",
    "postal": "",
    "city": "Badajoz",
    "province": "Badajoz",
    "country": "España",
    "phone": "+34 965 842 339",
    "email": "contacto@empresa75.example",
    "website": "www.empresa75.example",
    "industry": "Tecnología",
    "type": "prospecto",
    "priority": 2,
    "value": 400000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 38.9141,
    "lng": -6.98371,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Energía Serena S.A.",
    "contact": "Sergio Iglesias",
    "title": "Gerente",
    "address": "Rua da Liberdade 8",
    "postal": "",
    "city": "Badajoz",
    "province": "Badajoz",
    "country": "España",
    "phone": "+34 913 142 241",
    "email": "contacto@empresa76.example",
    "website": "www.empresa76.example",
    "industry": "Energía",
    "type": "cliente",
    "priority": 3,
    "value": 25000,
    "lastVisit": "2024-10-07",
    "duration": null,
    "notes": "",
    "lat": 38.90304,
    "lng": -6.94229,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Solar Mediterránea Group",
    "contact": "Javier Ferreira",
    "title": "Director Comercial",
    "address": "Calle Alcalá 29",
    "postal": "",
    "city": "Cáceres",
    "province": "Cáceres",
    "country": "España",
    "phone": "+34 914 135 968",
    "email": "contacto@empresa77.example",
    "website": "www.empresa77.example",
    "industry": "Energía",
    "type": "prospecto",
    "priority": 3,
    "value": 180000,
    "lastVisit": "",
    "duration": null,
    "notes": "",
    "lat": 39.51431,
    "lng": -6.35662,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Distribuciones Atlántica S.A.",
    "contact": "Nuria Navarro",
    "title": "Director Financiero",
    "address": "Avenida del Puerto 6",
    "postal": "",
    "city": "Cáceres",
    "province": "Cáceres",
    "country": "España",
    "phone": "+34 954 362 389",
    "email": "contacto@empresa78.example",
    "website": "www.empresa78.example",
    "industry": "Retail",
    "type": "cliente",
    "priority": 1,
    "value": 60000,
    "lastVisit": "2025-09-07",
    "duration": null,
    "notes": "",
    "lat": 39.50119,
    "lng": -6.38824,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Datos Vega Group",
    "contact": "Jorge Ribeiro",
    "title": "Responsable de Operaciones",
    "address": "Calle Real 121",
    "postal": "",
    "city": "Lisboa",
    "province": "Lisboa",
    "country": "Portugal",
    "phone": "+351 932 149 650",
    "email": "contacto@empresa79.example",
    "website": "www.empresa79.example",
    "industry": "Tecnología",
    "type": "prospecto",
    "priority": 1,
    "value": 15000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 38.74803,
    "lng": -9.09996,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Solar Ebro & Cía.",
    "contact": "Andrés Mota",
    "title": "Responsable de Operaciones",
    "address": "Camino de la Estación 178",
    "postal": "",
    "city": "Lisboa",
    "province": "Lisboa",
    "country": "Portugal",
    "phone": "+351 935 945 288",
    "email": "contacto@empresa80.example",
    "website": "www.empresa80.example",
    "industry": "Energía",
    "type": "cliente",
    "priority": 3,
    "value": 15000,
    "lastVisit": "2026-07-01",
    "duration": 90,
    "notes": "",
    "lat": 38.73341,
    "lng": -9.08444,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Restauración Serena S.A.",
    "contact": "Sergio Sánchez",
    "title": "Responsable de Operaciones",
    "address": "Camino de la Estación 179",
    "postal": "",
    "city": "Lisboa",
    "province": "Lisboa",
    "country": "Portugal",
    "phone": "+351 927 905 207",
    "email": "contacto@empresa81.example",
    "website": "www.empresa81.example",
    "industry": "Hostelería",
    "type": "cliente",
    "priority": 3,
    "value": 60000,
    "lastVisit": "2025-02-10",
    "duration": 60,
    "notes": "",
    "lat": 38.70497,
    "lng": -9.15115,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Automoción Levante & Cía.",
    "contact": "Iván Silva",
    "title": "Director Financiero",
    "address": "Paseo de la Constitución 129",
    "postal": "",
    "city": "Porto",
    "province": "Porto",
    "country": "Portugal",
    "phone": "+351 915 488 745",
    "email": "contacto@empresa82.example",
    "website": "www.empresa82.example",
    "industry": "Automoción",
    "type": "prospecto",
    "priority": 3,
    "value": 60000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 41.21117,
    "lng": -8.67387,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Renovables Alba S.L.",
    "contact": "Tiago Navarro",
    "title": "Gerente",
    "address": "Camino de la Estación 113",
    "postal": "",
    "city": "Porto",
    "province": "Porto",
    "country": "Portugal",
    "phone": "+351 932 891 363",
    "email": "contacto@empresa83.example",
    "website": "www.empresa83.example",
    "industry": "Energía",
    "type": "cliente",
    "priority": 2,
    "value": 40000,
    "lastVisit": "2025-03-31",
    "duration": 45,
    "notes": "",
    "lat": 41.11303,
    "lng": -8.63366,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Obras Castellana S.L.U.",
    "contact": "Lucía Ferreira",
    "title": "Responsable de Calidad",
    "address": "Calle Colón 134",
    "postal": "",
    "city": "Porto",
    "province": "Porto",
    "country": "Portugal",
    "phone": "+351 921 264 341",
    "email": "contacto@empresa84.example",
    "website": "www.empresa84.example",
    "industry": "Construcción",
    "type": "prospecto",
    "priority": 1,
    "value": 40000,
    "lastVisit": "",
    "duration": 60,
    "notes": "",
    "lat": 41.2126,
    "lng": -8.65806,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Transportes Atlántica S.A.",
    "contact": "Jorge Silva",
    "title": "Director Comercial",
    "address": "Avenida de la Industria 164",
    "postal": "",
    "city": "Braga",
    "province": "Braga",
    "country": "Portugal",
    "phone": "+351 939 209 387",
    "email": "contacto@empresa85.example",
    "website": "www.empresa85.example",
    "industry": "Logística y transporte",
    "type": "cliente",
    "priority": 1,
    "value": 90000,
    "lastVisit": "2025-09-04",
    "duration": 45,
    "notes": "",
    "lat": 41.59163,
    "lng": -8.43083,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Automoción Aurora Group",
    "contact": "Lucía Silva",
    "title": "Director Financiero",
    "address": "Calle Mayor 63",
    "postal": "",
    "city": "Coimbra",
    "province": "Coimbra",
    "country": "Portugal",
    "phone": "+351 939 973 540",
    "email": "contacto@empresa86.example",
    "website": "www.empresa86.example",
    "industry": "Automoción",
    "type": "prospecto",
    "priority": 3,
    "value": 15000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 40.24482,
    "lng": -8.39015,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Energía Ebro S.L.",
    "contact": "Jorge Ferreira",
    "title": "Director Financiero",
    "address": "Rua da Liberdade 162",
    "postal": "",
    "city": "Coimbra",
    "province": "Coimbra",
    "country": "Portugal",
    "phone": "+351 915 356 969",
    "email": "contacto@empresa87.example",
    "website": "www.empresa87.example",
    "industry": "Energía",
    "type": "prospecto",
    "priority": 2,
    "value": 25000,
    "lastVisit": "",
    "duration": 90,
    "notes": "",
    "lat": 40.20123,
    "lng": -8.46794,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Grupo Ebro S.L.U.",
    "contact": "Javier Martínez",
    "title": "Jefe de Planta",
    "address": "Paseo de la Constitución 56",
    "postal": "",
    "city": "Aveiro",
    "province": "Aveiro",
    "country": "Portugal",
    "phone": "+351 915 833 900",
    "email": "contacto@empresa88.example",
    "website": "www.empresa88.example",
    "industry": "Hostelería",
    "type": "prospecto",
    "priority": 2,
    "value": 250000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 40.64281,
    "lng": -8.70167,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Hoteles Occidental Group",
    "contact": "Nuria Vidal",
    "title": "Responsable de Mantenimiento",
    "address": "Calle Alcalá 176",
    "postal": "",
    "city": "Setúbal",
    "province": "Setúbal",
    "country": "Portugal",
    "phone": "+351 915 501 626",
    "email": "contacto@empresa89.example",
    "website": "www.empresa89.example",
    "industry": "Hostelería",
    "type": "cliente",
    "priority": 1,
    "value": 120000,
    "lastVisit": "2025-01-17",
    "duration": null,
    "notes": "",
    "lat": 38.55189,
    "lng": -8.87452,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Distribuciones Andalusí & Cía.",
    "contact": "Andrés Ortega",
    "title": "Jefe de Planta",
    "address": "Avenida de la Industria 58",
    "postal": "",
    "city": "Évora",
    "province": "Évora",
    "country": "Portugal",
    "phone": "+351 919 859 510",
    "email": "contacto@empresa90.example",
    "website": "www.empresa90.example",
    "industry": "Retail",
    "type": "cliente",
    "priority": 3,
    "value": 180000,
    "lastVisit": "2024-09-30",
    "duration": 45,
    "notes": "",
    "lat": 38.63071,
    "lng": -7.8582,
    "geoStatus": "ok",
    "tags": []
  },
  {
    "name": "Aceros Levante S.A.",
    "contact": "Lucía Iglesias",
    "title": "Director Financiero",
    "address": "Camino de la Estación 76",
    "postal": "",
    "city": "Faro",
    "province": "Faro",
    "country": "Portugal",
    "phone": "+351 934 661 765",
    "email": "contacto@empresa91.example",
    "website": "www.empresa91.example",
    "industry": "Metalurgia",
    "type": "prospecto",
    "priority": 2,
    "value": 60000,
    "lastVisit": "",
    "duration": 45,
    "notes": "",
    "lat": 37.05298,
    "lng": -7.93407,
    "geoStatus": "ok",
    "tags": []
  }
];
})(window.BTP);
